### ISSUE TITLE
Organization of binaries

### ISSUE THREAD

**Issue by crcrewso** [esimiele/VMAT-TBI-CSI#13]
To keep the PublishedScripts folders maintainable I propose a new layout

- PublishScripts/
  - launcher.cs
  - VMAT-TBI-CSI/
    - configurations/
    - documents/
    - logs/
    - all binaries 

What are the groups thoughts?

**Comment by esimiele** [comment]
I like it. I need to push a fix for the documentation since those buttons don't work properly. I'll incorporate this new folder structure in the next release (in the next few days/week). By default the scripts will read the documentation and write the logs to/from those folders (of course, this can be overridden).

**Comment by esimiele** [comment]
Binary structure has been revised. Please see updated code on master branch.
