### ISSUE TITLE
CSI VMAT Optimization Loop

### ISSUE THREAD

**Issue by fivey94** [esimiele/VMAT-TBI-CSI#21]
I'm getting a strange error with priority assignment with the Optimization loop for CSI patients. The ring structure seems to calculate as NaN for the dose diff^2 portion. I've tried touching up the structure but I'm still not having any luck. It has happened twice now.  This is for a C-arm machine.
No changes have been made to the original Optimization Loop coding. 

[Omega_CSI_VMATOptimization_LogFile.txt](https://github.com/user-attachments/files/15916809/Omega_CSI_VMATOptimization_LogFile.txt)
[Omega_CSI_VMATOptimization_LogFile2.txt](https://github.com/user-attachments/files/15916810/Omega_CSI_VMATOptimization_LogFile2.txt)

**Comment by esimiele** [comment]
Yeah, I've seen this before. It usually happens when the dose grid doesn't entirely contain a structure or if the sampling coverage is much less than 100%. If either of these happens, when the code tries to retrieve the dose metrics, it will return NaN, which messes up the optimization cost calculation. An easy way to check is to (manually) calculate dose in Eclipse for the initial plan and look at the dose statistics tab and see if any of the structures have dose coverage < 100% of sampling coverage << 100%
